modLoader="javafml"
loaderVersion="[30,)"
issueTrackerURL="https://github.com/jaquadro/StorageDrawers/issues"
displayURL="https://minecraft.curseforge.com/projects/storagedrawers"
authors="Texelsaur"

[[mods]]
    modId="storagedrawers"
    version="${version}"
    displayName="Storage Drawers"
    description='''
    Multi-drawer storage blocks for quick storage and retrieval.
    '''

[[dependencies.storagedrawers]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.storagedrawers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15,)"
    ordering="NONE"
    side="BOTH"