modLoader="javafml"
loaderVersion="[${loader_version},)"
issueTrackerURL="https://github.com/jaquadro/StorageDrawers/issues"
displayURL="https://minecraft.curseforge.com/projects/storagedrawers"
authors="Texelsaur"
license="MIT"

[[mods]]
    modId="storagedrawers"
    version="${version}"
    displayName="Storage Drawers"
    description='''
    Multi-drawer storage blocks for quick storage and retrieval.
    '''

[[dependencies.storagedrawers]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version}]"
    side="BOTH"
[[dependencies.storagedrawers]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"